version: "3.8"
services:
  web:
    container_name: needforheat-manual-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./source:/source
    environment:
      - NFH_MANUAL_SOURCE=https://github.com/energietransitie/needforheat-manuals.git
      - NFH_MANUAL_SOURCE_BRANCH=tst
      - NFH_FALLBACK_LANG=en-US